### ISSUE TITLE
publisher only load the tasklist on maya

### ISSUE THREAD

**Issue by willDTF** [cgwire/kitsu-publisher-deprecated#58]
at opening, kitsupublisher only open the tasklist part of the publisher window and return an error
![image](https://user-images.githubusercontent.com/4272733/116039996-beef5700-a66b-11eb-9045-5883cbacbfeb.png)

clicking the details or cancel button does nothing. maya console return : 
`=== An error occured !=== 
Error message:
Traceback (most recent call last):
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/kitsupublisher/views/MainWindow.py", line 118, in run
    self.function(self.args, **self.kwargs)
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/kitsupublisher/views/MainWindow.py", line 79, in set_up_thread_listeners
    create_event(events, self.table_updated)
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/kitsupublisher/utils/connection.py", line 60, in create_event
    event_client = gazu.events.init()
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/gazu/events.py", line 18, in init
    main_namespace = event_client.define(BaseNamespace, "/events")
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/socketIO_client/init.py", line 381, in define
    self.wait(for_namespace=namespace)
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/socketIO_client/init.py", line 251, in wait
    self._process_packets()
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/socketIO_client/init.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/socketIO_client/init.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/mnt/Pipeline/Test/kitsupublisher/kitsuPublisher/lib/python2.7/site-packages/socketIO_client/init.py", line 523, in _on_error
    namespace._find_packet_callback('error')(data_parsed.args)
TypeError: on_error() takes exactly 2 arguments (1 given)
// Warning: Panel size cannot accommodate all requested Heads Up Display elements. //`

and the terminal launching maya return : 
`QObject::setParent: Cannot set parent, new parent is in a different thread
QApplication: Object event filter cannot be in a different thread.`

 this issue occur on maya 2019 - centos 7.8 - python 2.7

**Comment by frankrousseau** [comment]
Thank you @Kaiz3rTool for reporting. We will have a look at this.

**Comment by Kaiz3rTool** [comment]
hello, 
a small update on this, the problem is exactly the same in houdini 18.5

**Comment by ddesmond** [comment]
@Kaiz3rTool can you please check what kitsu version do you run? you can check that in the browser while logged in and clicking on your name. let me know :) thanks

**Comment by Kaiz3rTool** [comment]
Hi, I use kitsu 0.12.59

**Comment by ddesmond** [comment]
@Kaiz3rTool more questions, do you self host kitsu? means not CGwire provided? is it a docker image or "regular" install using the guide from deplying kitsu/zou etc?

**Comment by Kaiz3rTool** [comment]
Sorry  i forgotten to mention that.
Yes it's self hosted, following the install guide
Zou's host OS is ubuntu LTS
The database is on an other server running on centos and postgres 12

From web interface everything runs well

**Comment by ddesmond** [comment]
Thanks for info! :)  It confirms some suspicions  I had about it. 
Needs more digging, ill update you when I have a solution.

**Comment by Kaiz3rTool** [comment]
Thanks !

**Comment by Kaiz3rTool** [comment]
hi, any news on this ? I still can't use kitsu publisher for now
thank you
